### PR TITLE
Add default $package_name value for SLES and openSUSE

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by n1tr0g** [comment]
Tnx Theo ... Would you mind to add also the rspec tests for this change ?

**Comment by tampakrap** [comment]
sure, on it

**Comment by tampakrap** [comment]
Added SUSE in the spec/class tests but not in the acceptance ones. I'd like to also suggest you the [puppet_spec_facts](https://github.com/danieldreier/puppet_spec_facts) module for the class rspec tests

**Comment by tampakrap** [comment]
anything else missing from my side?

**Comment by n1tr0g** [comment]
Hmmm optionally could you tell me which operating system releases are  supported, so I can update metadata.json accordingly.

**Comment by tampakrap** [comment]
SLES 12 and openSUSE 13.2, but putting only SLES in metadata.json should be sufficient

**Comment by n1tr0g** [comment]
tnx i will release a new version tonight ... tnx again for the commit

**Pull request merged**
